### ISSUE TITLE
How can you get the training data？

### ISSUE THREAD

**Issue by oiwio** [yscacaca/DeepSense#1]
I noticed that the data you shared is different from the original data, can you share your code that for data processing? Thanks for your sharing!!!

**Comment by yscacaca** [comment]
Hi,

I've opened a new repository for the data-processing code
[https://github.com/yscacaca/HHAR-Data-Process](url)

**Comment by oiwio** [comment]
您的代码里实践的是HHAR的例子，想请教下，如果是做UserID的问题，确定当前手机用户是不是本人，作为一个二分类问题，如何找到足够多的“不是本人”数据来确保模型的准确度呢？

**Comment by yscacaca** [comment]
如果没有privacy issue的话，可以用别人手机的数据作为negative samples。

**Comment by oiwio** [comment]
这儿的[mataDict](https://github.com/yscacaca/DeepSense/blob/master/deepSense_HHAR_tf.py#L33)是作为什么用的呢？下面的TRAIN_SIZE并没有用到，但是EVAL_ITER_NUM用到了，这儿['a':[119080, 1193]](https://github.com/yscacaca/DeepSense/blob/master/deepSense_HHAR_tf.py#L33)是哪儿来的呢？

**Comment by yscacaca** [comment]
mataDict 包含的是training和testing data的数量

**Comment by FelixHuiweiLin** [comment]
您好，请问您是否还保存了原始数据？数据原文提供的链接貌似已经失效
