### ISSUE TITLE
I don't clear how you calculated the capacity/min_after_deque value when getting the batch 

### ISSUE THREAD

**Issue by shamanez** [yscacaca/DeepSense#10]
In this [This line](https://github.com/yscacaca/DeepSense/blob/master/deepSense_HHAR_tf.py#L54). 

These things mainly control how to extract a batch from the que. So assigning them incorrectly can cause errors. So can you please explain ?

**Comment by yscacaca** [comment]
min_after_dequeue is the minimum number elements in the queue after a dequeue, which is used to ensure a level of mixing of elements. Is it because you set min_after_dequeue to be a value that is too large?
