### ISSUE TITLE
Does this kind of convolution preserve the time time distributed convolution ?

### ISSUE THREAD

**Issue by shamanez** [yscacaca/DeepSense#11]
In the keras there's [TimeDistributed](https://keras.io/layers/wrappers/) wrapper where we can use to do convolution for each time step.  So I think by feeding the tensor with Batch Size , Sequence Length , .. etc we can have the same property. Am I right ?

**Comment by yscacaca** [comment]
The TimeDistributed wrapper should have the same property we want. You probably can set keras.layers.convolutional.Conv1D with the TimeDistributed wrapper.

**Comment by shamanez** [comment]
Yeah. So main thing is we need to feed a tensor with sequence .
