### ISSUE TITLE
This is bit slow when start training ?

### ISSUE THREAD

**Issue by shamanez** [yscacaca/DeepSense#13]
Why this is bit slow . What is the reason ? Do you think it's because of the #5 issue the input/output stream ?

**Comment by yscacaca** [comment]
There is something not so efficient about I/O. Yes, please refer to [#5](https://github.com/yscacaca/DeepSense/issues/5) for the solution.

**Comment by shamanez** [comment]
I found the reason. Inside the session when it starts iteration it take lot of time to run [this line](https://github.com/yscacaca/DeepSense/blob/master/deepSense_HHAR_tf.py#L269) . I think there the model is loading the data to the reader queue.
