### ISSUE TITLE
Parameters about the "layers.batch_norm" function you used in : Does they have an impact on the overall result ?

### ISSUE THREAD

**Issue by shamanez** [yscacaca/DeepSense#18]
In this [line](https://github.com/yscacaca/DeepSense/blob/master/deepSense_HHAR_tf.py#L76) for the function **layers.batch_norm** you have used 

> updates_collections=None

So what if we use **_updates_collections=tf.GraphKeys.UPDATE_OPS_**

In order to work this we need to explicitly update the GraphKeys class rel event to moving averages .
```

  update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
  with tf.control_dependencies(update_ops):
    train_op = optimizer.minimize(loss)
```

Also the TF document says , 

> One can set updates_collections=None to force the updates in place, but that can have a speed penalty, especially in distributed settings.

**Comment by yscacaca** [comment]
You can also tf.GraphKeys.UPDATE_OPS by referring the TensorFlow documents. I haven't tried that yet.
