### ISSUE TITLE
Deploying on Android

### ISSUE THREAD

**Issue by dmazzoni** [yscacaca/DeepSense#21]
I would like to test the neural network in an Android app, by importing the frozen and optimized model with TF's `TensorFlowInferenceInterface`. I have edited the `deepSense_HHAR_tf.py` source to export the evaluation model in PB and PBTXT formats, and exported a checkpoint using `tf.train.Saver`. Then, I applied TF's `freeze_graph` tool.

In the Android application I can successfully load the model and feed the input parsed from the CSV files, but trying to run it yields the following exception:

`No OpKernel was registered to support Op 'FIFOQueueV2' with these attrs.  Registered devices: [CPU], Registered kernels: no registered kernels`

This is probably due to Android's TensorFlow library not including the specified Op.

I have then applied TF's `optimize_for_inference` tool to the frozen graph, and imported the output in the Android app, but with this approach an exception is immediately thrown upon loading the model:

`NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: deepSense_1/rnn/while/add/y = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 1>](deepSense_1/rnn/while/Switch:1)`

Do you have some advice on exporting the model for Android, based on your experience with the Nexus 5?

**Comment by yscacaca** [comment]
Sorry for replying late. I was traveling during the last week. 
Before I did the experiments on Android with MXNet. I will find some time to test this code on Android and see what's happened.

**Comment by dmazzoni** [comment]
Thanks for your reply! To test the model on Android, I would be ok with switching to MXNet. Do you already have an implementation akin to the one in `deepSense_HHAR_tf.py` which uses MXNet instead of Tensorflow?

**Comment by yscacaca** [comment]
I do not have code used for training DeepSense with MXNet for now. I can rewrite the code in MXNet in next week. But I probably will first test the problem of Tensorflow on Android and see what happens.

**Comment by dmazzoni** [comment]
Ok, thanks for the feedback!

**Comment by dmazzoni** [comment]
@yscacaca Did you have the time to test TF on Android?

**Comment by yscacaca** [comment]
Sorry again for replying late. 
I've tested the DeepSense with tf1.4 on Android today.  The error that you've encountered is mainly due to the "control dependency" within the code. So I just write [an evaluation version by loading a trained model and saving a new model used for evaluation](https://github.com/yscacaca/DeepSense/tree/master/android_test), where these "control dependencies" can be deleted. Then, with the "freeze and optimize" steps, the generated .pb file at least can run within Android app without any errors.

**Comment by yscacaca** [comment]
I made a mistake in my last reply.
The main reason for the error is the Conv3D operation in the deepSense code.
I [rewirte the code to bypass the problem](https://github.com/yscacaca/DeepSense/tree/master/android_test). Now, it should work well on Android.

**Comment by dmazzoni** [comment]
Thank you very much for your support! Now I can run my Android test application without errors
