### ISSUE TITLE
what's the meaning of mode = 'one_user_out' and select = 'a'

### ISSUE THREAD

**Issue by kaixinbuyu** [yscacaca/DeepSense#4]
in data preprocessing stage,what's the meaning of:
1.  mode = 'one_user_out'  usd for?
2.  select = 'a'    usd for?

**Comment by zhezh** [comment]
`csvDataFolder1 = os.path.join('sepHARData_'+select, "train")`
I believe this is for choosing data folder

**Comment by yscacaca** [comment]
I suppose that you are talking about the code [here](https://github.com/yscacaca/HHAR-Data-Process/blob/master/sep_HHAR_data.py). 
1. mode here means the way we select training/evalution data. When mode='one_user_out', we select all the data from one user for evaluation and and others for training. 
2. select = 'a' means that we select user 'a' out for evaluation.
