### ISSUE TITLE
training is slow and utilize only a few gpu resources

### ISSUE THREAD

**Issue by zhezh** [yscacaca/DeepSense#5]
I tried train this model with data provided in readme, I find the training procedure is slow. It already has taken more than 2 hours to just iterate about 700 times.
I watch the usage of gpu and cpu, gpu usage is about 10%~20%, sometimes even low to 0%~3%, cpu usage is about 50%, sometimes drop to near 0.
CPU usage diagram is as below
![screenshot from 2017-09-04 18-47-12](https://user-images.githubusercontent.com/29795174/30023364-9333d2a4-91a1-11e7-92f8-395d44f55023.png)

My laptop is with intel i7 6700k and gtx 1050ti. I run the code in pycharm with python 2.7 and tensorflow 1.3.

**Comment by yscacaca** [comment]
I believe there is something not so efficient with the I/O part. You can try reading all training data into the memory if your machine allows. It should boost up the training speed.

**Comment by zhezh** [comment]
Yes, you are right! I copy all the data from hdd to ssd partition, the training speed increased to more than twice.

I use glances to watch IO usage, the IO is about 4M, still low.

Maybe we can try use tfrecord to put all data into one file and then read it with streaming method to avoid reading a lot of little files if we lack RAM resources.

**Comment by zhezh** [comment]
@yscacaca  Hey, I write a version using tfrecord to boost training speed. If you are interested, see [this link](https://github.com/zhezh/DeepSense)

**Comment by yscacaca** [comment]
Cool, thank you @zhezh !

**Comment by kaixinbuyu** [comment]
@zhezh     
I meet an error:
'example': tf.train.Feature(float_list=tf.train.FloatList(value=features))
TypeError: Value must be iterable


example = tf.train.Example(
        features=tf.train.Features(
            feature={
                "label": tf.train.Feature(float_list=tf.train.FloatList(value=label)),
                'example': tf.train.Feature(float_list=tf.train.FloatList(value=features))  <--error here
            }
        )
    )

**Comment by zhezh** [comment]
@kaixinbuyu 
Maybe you could debug it to see what is actually passed to this function.

**Comment by kaixinbuyu** [comment]
def csv_to_example(fname):
    text = np.loadtxt(fname, delimiter=',')
    features = text[:WIDE*FEATURE_DIM]
    label = text[WIDE*FEATURE_DIM:]
    **features = tf.reshape(features, [WIDE, FEATURE_DIM])**

    example = tf.train.Example(features=tf.train.Features(feature={
        "label": tf.train.Feature(float_list=tf.train.FloatList(value=label)),
        'example': tf.train.Feature(float_list=tf.train.FloatList(value=features))
    }))

    return example

@zhezh 
Im using tensorflow1.2.Which tensorflow version are you running this code?
Does tfrecord support mutil-dim tensor（ tf.reshape(features）as input param？or It only support one-dim float32 list.
The error showes that tf.reshape tensor can not convert to list as tf.train.FloatList's input.

**Comment by kaixinbuyu** [comment]
@zhezh remove the reshape line 
features = tf.reshape(features, [WIDE, FEATURE_DIM])
and reshape while reading tfrecord file seems ok.

**Comment by shamanez** [comment]
@kaixinbuyu I also have the same error can you please tell me how did you fix it ?
